[build]
  publish = "/"
  command = "# no build command needed"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/blogs/*"
  to = "/blogs/index.html"
  status = 200 