# Backend configuration
backend:
  name: git-gateway
  branch: main
  repo: zaidhajeer/Portfolio
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'

# Media configuration
media_folder: "assets/images/blog"
public_folder: "/assets/images/blog"

# CMS Configuration
locale: 'en'
show_preview_links: true
publish_mode: editorial_workflow

# Site URLs
site_url: https://portfoliozaidhajeer.netlify.app
display_url: https://portfoliozaidhajeer.netlify.app

# Collections
collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "blogs/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "blogs/posts/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Author", name: "author", widget: "string", default: "Zaid Hajeer", required: true}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", required: true}
      - {label: "Featured Image", name: "image", widget: "image", required: true}
      - {label: "Category", name: "category", widget: "select", options: ["Web Development", "UI/UX Design", "Programming", "Career Tips", "Technology"], required: true}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Description", name: "description", widget: "text", required: true}
      - {label: "Content", name: "body", widget: "markdown", required: true}
    editor:
      preview: true
      frame: true