backend:
  name: git-gateway
  branch: main
  repo: zaidhajeer/Portfolio

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "blogs"
    create: true
    format: "json"
    extension: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "content", widget: "markdown" }
    preview_template: "template.html"
    hooks:
      afterChange:
        - trigger: "updatePosts"

<script src="https://identity.netlify.com/v1/netlify-identity-widget.js"></script> 